// Starter template definitions

export const starterTemplates = {
  invoice: [
    {
      id: 'modern-invoice',
      name: 'Modern Invoice',
      description: 'Clean and professional invoice with bold headers',
      preview: '/templates/previews/modern-invoice.png',
      template: {
        type: 'invoice' as const,
        name: 'Modern Invoice',
        description: 'Professional invoice template with modern design',
        pageSetup: {
          size: 'letter' as const,
          orientation: 'portrait' as const,
          margins: { top: 48, right: 48, bottom: 48, left: 48 },
        },
        branding: {
          primaryColor: '#3f72af',
          secondaryColor: '#1a1a1a',
          fontFamily: 'Inter',
        },
        components: [
          {
            id: 'header-1',
            type: 'header' as const,
            position: { x: 60, y: 60 },
            size: { width: 700, height: 60 },
            content: { text: 'INVOICE', size: 'xl' },
            styles: {
              fontSize: 36,
              fontWeight: 'bold',
              color: '#3f72af',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 0,
            },
          },
          {
            id: 'company-info-1',
            type: 'company-info' as const,
            position: { x: 60, y: 140 },
            size: { width: 350, height: 150 },
            content: {
              showLogo: true,
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 14,
              color: '#1a1a1a',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
          {
            id: 'customer-info-1',
            type: 'customer-info' as const,
            position: { x: 450, y: 140 },
            size: { width: 310, height: 150 },
            content: {
              title: 'Bill To:',
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 14,
              color: '#1a1a1a',
              backgroundColor: '#f9fafb',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
          {
            id: 'line-items-1',
            type: 'line-items' as const,
            position: { x: 60, y: 320 },
            size: { width: 700, height: 200 },
            content: {
              columns: ['Description', 'Quantity', 'Rate', 'Amount'],
              showSubtotal: true,
            },
            styles: {
              fontSize: 14,
              color: '#1a1a1a',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
          {
            id: 'totals-1',
            type: 'totals' as const,
            position: { x: 460, y: 550 },
            size: { width: 300, height: 150 },
            content: {
              showSubtotal: true,
              showTax: true,
              showDiscount: false,
              showTotal: true,
            },
            styles: {
              fontSize: 14,
              color: '#1a1a1a',
              backgroundColor: '#ffffff',
              textAlign: 'right' as const,
              padding: 16,
            },
          },
          {
            id: 'text-1',
            type: 'text' as const,
            position: { x: 60, y: 730 },
            size: { width: 700, height: 80 },
            content: { text: 'Payment Terms: Net 30 days\nThank you for your business!' },
            styles: {
              fontSize: 12,
              color: '#6b7280',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
        ],
      },
    },
    {
      id: 'classic-invoice',
      name: 'Classic Invoice',
      description: 'Traditional invoice layout with centered header',
      preview: '/templates/previews/classic-invoice.png',
      template: {
        type: 'invoice' as const,
        name: 'Classic Invoice',
        description: 'Traditional invoice design',
        pageSetup: {
          size: 'letter' as const,
          orientation: 'portrait' as const,
          margins: { top: 48, right: 48, bottom: 48, left: 48 },
        },
        branding: {
          primaryColor: '#1e40af',
          secondaryColor: '#374151',
          fontFamily: 'Inter',
        },
        components: [
          {
            id: 'header-2',
            type: 'header' as const,
            position: { x: 60, y: 60 },
            size: { width: 700, height: 80 },
            content: { text: 'INVOICE', size: 'xl' },
            styles: {
              fontSize: 42,
              fontWeight: 'bold',
              color: '#1e40af',
              backgroundColor: '#eff6ff',
              textAlign: 'center' as const,
              padding: 20,
            },
          },
          {
            id: 'company-info-2',
            type: 'company-info' as const,
            position: { x: 60, y: 170 },
            size: { width: 700, height: 100 },
            content: {
              showLogo: true,
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 13,
              color: '#374151',
              backgroundColor: '#ffffff',
              textAlign: 'center' as const,
              padding: 12,
            },
          },
          {
            id: 'customer-info-2',
            type: 'customer-info' as const,
            position: { x: 60, y: 300 },
            size: { width: 340, height: 140 },
            content: {
              title: 'BILL TO',
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 14,
              color: '#1f2937',
              backgroundColor: '#f3f4f6',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
          {
            id: 'line-items-2',
            type: 'line-items' as const,
            position: { x: 60, y: 470 },
            size: { width: 700, height: 220 },
            content: {
              columns: ['Description', 'Qty', 'Rate', 'Amount'],
              showSubtotal: true,
            },
            styles: {
              fontSize: 14,
              color: '#111827',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
          {
            id: 'totals-2',
            type: 'totals' as const,
            position: { x: 460, y: 720 },
            size: { width: 300, height: 140 },
            content: {
              showSubtotal: true,
              showTax: true,
              showDiscount: true,
              showTotal: true,
            },
            styles: {
              fontSize: 14,
              color: '#111827',
              backgroundColor: '#f9fafb',
              textAlign: 'right' as const,
              padding: 16,
            },
          },
        ],
      },
    },
  ],
  estimate: [
    {
      id: 'professional-estimate',
      name: 'Professional Estimate',
      description: 'Detailed estimate with project information',
      preview: '/templates/previews/professional-estimate.png',
      template: {
        type: 'estimate' as const,
        name: 'Professional Estimate',
        description: 'Comprehensive estimate template',
        pageSetup: {
          size: 'letter' as const,
          orientation: 'portrait' as const,
          margins: { top: 48, right: 48, bottom: 48, left: 48 },
        },
        branding: {
          primaryColor: '#059669',
          secondaryColor: '#064e3b',
          fontFamily: 'Inter',
        },
        components: [
          {
            id: 'header-3',
            type: 'header' as const,
            position: { x: 60, y: 60 },
            size: { width: 700, height: 70 },
            content: { text: 'PROJECT ESTIMATE', size: 'xl' },
            styles: {
              fontSize: 32,
              fontWeight: 'bold',
              color: '#ffffff',
              backgroundColor: '#059669',
              textAlign: 'center' as const,
              padding: 18,
            },
          },
          {
            id: 'company-info-3',
            type: 'company-info' as const,
            position: { x: 60, y: 160 },
            size: { width: 340, height: 130 },
            content: {
              showLogo: true,
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 13,
              color: '#064e3b',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'customer-info-3',
            type: 'customer-info' as const,
            position: { x: 420, y: 160 },
            size: { width: 340, height: 130 },
            content: {
              title: 'Prepared For:',
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 13,
              color: '#064e3b',
              backgroundColor: '#ecfdf5',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'text-3',
            type: 'text' as const,
            position: { x: 60, y: 320 },
            size: { width: 700, height: 60 },
            content: { text: 'Project Description:\nThis estimate includes all labor, materials, and equipment necessary for project completion.' },
            styles: {
              fontSize: 13,
              color: '#374151',
              backgroundColor: '#f9fafb',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'line-items-3',
            type: 'line-items' as const,
            position: { x: 60, y: 410 },
            size: { width: 700, height: 220 },
            content: {
              columns: ['Service Description', 'Qty', 'Unit Price', 'Total'],
              showSubtotal: true,
            },
            styles: {
              fontSize: 13,
              color: '#111827',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'totals-3',
            type: 'totals' as const,
            position: { x: 460, y: 660 },
            size: { width: 300, height: 140 },
            content: {
              showSubtotal: true,
              showTax: true,
              showDiscount: false,
              showTotal: true,
            },
            styles: {
              fontSize: 14,
              color: '#111827',
              backgroundColor: '#f0fdf4',
              textAlign: 'right' as const,
              padding: 16,
            },
          },
          {
            id: 'text-4',
            type: 'text' as const,
            position: { x: 60, y: 830 },
            size: { width: 700, height: 70 },
            content: { text: 'This estimate is valid for 30 days.\nA 50% deposit is required to begin work.' },
            styles: {
              fontSize: 12,
              color: '#6b7280',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
        ],
      },
    },
  ],
  agreement: [
    {
      id: 'service-agreement',
      name: 'Service Agreement',
      description: 'Professional service agreement with signature fields',
      preview: '/templates/previews/service-agreement.png',
      template: {
        type: 'agreement' as const,
        name: 'Service Agreement',
        description: 'Standard service agreement template',
        pageSetup: {
          size: 'letter' as const,
          orientation: 'portrait' as const,
          margins: { top: 48, right: 48, bottom: 48, left: 48 },
        },
        branding: {
          primaryColor: '#7c3aed',
          secondaryColor: '#5b21b6',
          fontFamily: 'Inter',
        },
        components: [
          {
            id: 'header-4',
            type: 'header' as const,
            position: { x: 60, y: 60 },
            size: { width: 700, height: 80 },
            content: { text: 'SERVICE AGREEMENT', size: 'xl' },
            styles: {
              fontSize: 36,
              fontWeight: 'bold',
              color: '#7c3aed',
              backgroundColor: '#faf5ff',
              textAlign: 'center' as const,
              padding: 22,
            },
          },
          {
            id: 'company-info-4',
            type: 'company-info' as const,
            position: { x: 60, y: 170 },
            size: { width: 340, height: 120 },
            content: {
              showLogo: false,
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 13,
              color: '#5b21b6',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
          {
            id: 'customer-info-4',
            type: 'customer-info' as const,
            position: { x: 420, y: 170 },
            size: { width: 340, height: 120 },
            content: {
              title: 'Client:',
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: true,
            },
            styles: {
              fontSize: 13,
              color: '#5b21b6',
              backgroundColor: '#faf5ff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
          {
            id: 'text-5',
            type: 'text' as const,
            position: { x: 60, y: 320 },
            size: { width: 700, height: 240 },
            content: { text: 'TERMS AND CONDITIONS\n\n1. SCOPE OF SERVICES\nThe Service Provider agrees to provide the services as described in the attached schedule.\n\n2. PAYMENT TERMS\nPayment shall be made according to the payment schedule outlined below.\n\n3. TERM AND TERMINATION\nThis agreement shall commence on the date signed and continue until completion of services.' },
            styles: {
              fontSize: 12,
              color: '#374151',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
          {
            id: 'line-items-4',
            type: 'line-items' as const,
            position: { x: 60, y: 590 },
            size: { width: 700, height: 160 },
            content: {
              columns: ['Service', 'Frequency', 'Rate', 'Amount'],
              showSubtotal: true,
            },
            styles: {
              fontSize: 13,
              color: '#1f2937',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
          {
            id: 'signature-4',
            type: 'signature' as const,
            position: { x: 60, y: 780 },
            size: { width: 700, height: 140 },
            content: {
              lines: 2,
              labels: ['Client Signature', 'Service Provider Signature'],
            },
            styles: {
              fontSize: 12,
              color: '#374151',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 16,
            },
          },
        ],
      },
    },
  ],
  work_order: [
    {
      id: 'field-work-order',
      name: 'Field Work Order',
      description: 'Work order template for field services',
      preview: '/templates/previews/field-work-order.png',
      template: {
        type: 'work_order' as const,
        name: 'Field Work Order',
        description: 'Work order for field operations',
        pageSetup: {
          size: 'letter' as const,
          orientation: 'portrait' as const,
          margins: { top: 48, right: 48, bottom: 48, left: 48 },
        },
        branding: {
          primaryColor: '#ea580c',
          secondaryColor: '#9a3412',
          fontFamily: 'Inter',
        },
        components: [
          {
            id: 'header-5',
            type: 'header' as const,
            position: { x: 60, y: 60 },
            size: { width: 700, height: 70 },
            content: { text: 'WORK ORDER', size: 'xl' },
            styles: {
              fontSize: 34,
              fontWeight: 'bold',
              color: '#ffffff',
              backgroundColor: '#ea580c',
              textAlign: 'left' as const,
              padding: 18,
            },
          },
          {
            id: 'text-6',
            type: 'text' as const,
            position: { x: 600, y: 70 },
            size: { width: 160, height: 50 },
            content: { text: 'WO #: {{document.number}}\nDate: {{document.date}}' },
            styles: {
              fontSize: 11,
              color: '#ffffff',
              backgroundColor: '#ea580c',
              textAlign: 'right' as const,
              padding: 10,
            },
          },
          {
            id: 'customer-info-5',
            type: 'customer-info' as const,
            position: { x: 60, y: 160 },
            size: { width: 340, height: 130 },
            content: {
              title: 'Customer Information:',
              showName: true,
              showAddress: true,
              showPhone: true,
              showEmail: false,
            },
            styles: {
              fontSize: 13,
              color: '#9a3412',
              backgroundColor: '#fff7ed',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'text-7',
            type: 'text' as const,
            position: { x: 420, y: 160 },
            size: { width: 340, height: 130 },
            content: { text: 'Service Location:\n{{site.address}}\n\nScheduled: {{document.scheduled_date}}\nAssigned To: {{technician.name}}' },
            styles: {
              fontSize: 13,
              color: '#9a3412',
              backgroundColor: '#ffedd5',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'text-8',
            type: 'text' as const,
            position: { x: 60, y: 320 },
            size: { width: 700, height: 100 },
            content: { text: 'WORK TO BE PERFORMED:\n\nPlease describe the services and tasks to be completed during this visit.' },
            styles: {
              fontSize: 13,
              color: '#374151',
              backgroundColor: '#f9fafb',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'line-items-5',
            type: 'line-items' as const,
            position: { x: 60, y: 450 },
            size: { width: 700, height: 180 },
            content: {
              columns: ['Task/Service', 'Est. Time', 'Status', 'Notes'],
              showSubtotal: false,
            },
            styles: {
              fontSize: 13,
              color: '#111827',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
          {
            id: 'text-9',
            type: 'text' as const,
            position: { x: 60, y: 660 },
            size: { width: 700, height: 100 },
            content: { text: 'NOTES & OBSERVATIONS:\n\n_____________________________________________________________________\n_____________________________________________________________________' },
            styles: {
              fontSize: 12,
              color: '#6b7280',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 14,
            },
          },
          {
            id: 'signature-5',
            type: 'signature' as const,
            position: { x: 60, y: 790 },
            size: { width: 700, height: 120 },
            content: {
              lines: 2,
              labels: ['Customer Signature', 'Technician Signature'],
            },
            styles: {
              fontSize: 11,
              color: '#374151',
              backgroundColor: '#ffffff',
              textAlign: 'left' as const,
              padding: 12,
            },
          },
        ],
      },
    },
  ],
};

export function getStarterTemplates(type: 'invoice' | 'estimate' | 'agreement' | 'work_order') {
  return starterTemplates[type] || [];
}

export function getAllStarterTemplates() {
  return Object.values(starterTemplates).flat();
}
